import type { Product } from './types'

/**
 * Sky Phone's real catalogue - 27 SKUs, carried over verbatim from the shop's
 * existing site along with its approved trilingual descriptions. Prices are in
 * whole Israeli shekels (the shop does not price in agorot).
 *
 * Product photography lives in /public/img and is mirrored locally so the site
 * works offline. Provenance is mixed: most images come from Wikimedia Commons,
 * and some are official manufacturer imagery supplied by the shop owner. See
 * README for the rights note.
 *
 * This is generated data, which is why it is long; edit the catalogue here.
 */
export const products: readonly Product[] = [
  {
    id: "1",
    slug: "iphone-15-pro",
    name: "iPhone 15 Pro",
    categoryId: "phones",
    brand: "apple",
    icon: "phone",
    badge: "new",
    price: 4290,
    image: "/img/iphone15pro-naturaltitanium-1.png",
    images: ["/img/iphone15pro-naturaltitanium-1.png","/img/iphone15pro.png","/img/iphone15pro-2.jpg"],
    colors: [{ name: "Natural Titanium", hex: "#8a8479", images: ["/img/iphone15pro-naturaltitanium-1.png"] }, { name: "Blue Titanium", hex: "#3f4a56", images: ["/img/iphone15pro-bluetitanium-1.png"] }, { name: "White Titanium", hex: "#f2efe9", images: ["/img/iphone15pro-whitetitanium-1.png"] }, { name: "Black Titanium", hex: "#2b2a28", images: ["/img/iphone15pro-blacktitanium-1.png"] }],
    storage: [{ label: "128GB", delta: 0 }, { label: "256GB", delta: 400 }, { label: "512GB", delta: 900 }],
    description: {
      he: "iPhone 15 Pro עם שבב A17 Pro, מסך Super Retina XDR ומצלמה מקצועית — הדגם המבוקש ביותר אצלנו.",
      ar: "iPhone 15 Pro بشريحة A17 Pro وشاشة Super Retina XDR وكاميرا احترافية — الطراز الأكثر طلباً لدينا.",
      en: "iPhone 15 Pro with the A17 Pro chip, Super Retina XDR display and a pro camera system — our most requested model.",
    },
  },
  {
    id: "2",
    slug: "galaxy-s24-ultra",
    name: "Galaxy S24 Ultra",
    categoryId: "phones",
    brand: "samsung",
    icon: "phone",
    price: 4590,
    image: "/img/s24ultra.png",
    images: ["/img/s24ultra.png","/img/s24ultra-2.jpg"],
    colors: [{ name: "Titanium Black", hex: "#2b2b2e" }, { name: "Titanium Gray", hex: "#8a8a8d" }, { name: "Titanium Violet", hex: "#8a7ea3" }, { name: "Titanium Yellow", hex: "#d8c98a" }],
    storage: [{ label: "256GB", delta: 0 }, { label: "512GB", delta: 450 }, { label: "1TB", delta: 950 }],
    description: {
      he: "Galaxy S24 Ultra עם מסך AMOLED ענק, עט S Pen מובנה ומצלמה בזום גבוה.",
      ar: "Galaxy S24 Ultra بشاشة AMOLED كبيرة، قلم S Pen مدمج وكاميرا بتقريب عالٍ.",
      en: "Galaxy S24 Ultra with a large AMOLED display, built-in S Pen and high-zoom camera.",
    },
  },
  {
    id: "9",
    slug: "iphone-14",
    name: "iPhone 14",
    categoryId: "phones",
    brand: "apple",
    icon: "phone",
    price: 2990,
    image: "/img/iphone14-midnight-1.png",
    images: ["/img/iphone14-midnight-1.png","/img/iphone14.png","/img/iphone14-2.jpg"],
    colors: [{ name: "Midnight", hex: "#1d1d1f", images: ["/img/iphone14-midnight-1.png"] }, { name: "Starlight", hex: "#f0e6d8", images: ["/img/iphone14-starlight-1.png"] }, { name: "Blue", hex: "#5f7a99", images: ["/img/iphone14-blue-1.png"] }, { name: "(PRODUCT)RED", hex: "#a72032", images: ["/img/iphone14-productred-1.png"] }],
    storage: [{ label: "128GB", delta: 0 }, { label: "256GB", delta: 350 }, { label: "512GB", delta: 800 }],
    description: {
      he: "iPhone 14 — האמינות והביצועים של אפל במחיר נגיש יותר.",
      ar: "iPhone 14 — موثوقية وأداء آبل بسعر أكثر سهولة.",
      en: "iPhone 14 — Apple's reliability and performance at a more accessible price.",
    },
  },
  {
    id: "10",
    slug: "xiaomi-14",
    name: "Xiaomi 14",
    categoryId: "phones",
    brand: "xiaomi",
    icon: "phone",
    price: 2490,
    image: "/img/xiaomi14.jpg",
    images: ["/img/xiaomi14.jpg","/img/xiaomi14-2.jpg"],
    colors: [{ name: "Black", hex: "#1c1c1e" }, { name: "White", hex: "#eceae6" }, { name: "Jade Green", hex: "#6f8a72" }],
    storage: [{ label: "256GB", delta: 0 }, { label: "512GB", delta: 300 }],
    description: {
      he: "Xiaomi 14 — טלפון אנדרואיד רב עוצמה עם מצלמת Leica ותמורה מעולה למחיר.",
      ar: "Xiaomi 14 — هاتف أندرويد قوي بكاميرا Leica وقيمة ممتازة مقابل السعر.",
      en: "Xiaomi 14 — a powerful Android phone with a Leica camera and excellent value.",
    },
  },
  {
    id: "3",
    slug: "ipad-air",
    name: "iPad Air",
    categoryId: "tablets",
    brand: "apple",
    icon: "tablet",
    price: 2790,
    image: "/img/ipadair-spacegray-1.png",
    images: ["/img/ipadair-spacegray-1.png","/img/ipadair.jpg","/img/ipadair-2.jpg"],
    colors: [{ name: "Space Gray", hex: "#5b5c5f", images: ["/img/ipadair-spacegray-1.png"] }, { name: "Starlight", hex: "#f0e6d8", images: ["/img/ipadair-starlight-1.png"] }, { name: "Blue", hex: "#7fa7c9", images: ["/img/ipadair-blue-1.png"] }, { name: "Purple", hex: "#a99bc7", images: ["/img/ipadair-purple-1.png"] }],
    storage: [{ label: "128GB", delta: 0 }, { label: "256GB", delta: 350 }],
    description: {
      he: "iPad Air עם שבב M1 — קליל, חזק ומושלם לעבודה, לימודים ובידור.",
      ar: "iPad Air بشريحة M1 — خفيف وقوي ومثالي للعمل والدراسة والترفيه.",
      en: "iPad Air with the M1 chip — light, powerful, and perfect for work, study and play.",
    },
  },
  {
    id: "11",
    slug: "galaxy-tab-s9",
    name: "Galaxy Tab S9",
    categoryId: "tablets",
    brand: "samsung",
    icon: "tablet",
    price: 2690,
    image: "/img/tabs9.png",
    images: ["/img/tabs9.png","/img/tabs9-2.jpg"],
    colors: [{ name: "Graphite", hex: "#3a3b3e" }, { name: "Beige", hex: "#d9cdb8" }],
    storage: [{ label: "128GB", delta: 0 }, { label: "256GB", delta: 300 }],
    description: {
      he: "Galaxy Tab S9 — מסך AMOLED, עמידות למים ועט S Pen כלול בקופסה.",
      ar: "Galaxy Tab S9 — شاشة AMOLED، مقاومة للماء وقلم S Pen ضمن العلبة.",
      en: "Galaxy Tab S9 — AMOLED display, water resistance, and an S Pen included in the box.",
    },
  },
  {
    id: "4",
    slug: "macbook-air",
    name: "MacBook Air",
    categoryId: "computers",
    brand: "apple",
    icon: "laptop",
    badge: "new",
    price: 5490,
    image: "/img/macbookair-midnight-1.png",
    images: ["/img/macbookair-midnight-1.png","/img/macbook.png","/img/macbook-2.jpg"],
    colors: [{ name: "Midnight", hex: "#33363d", images: ["/img/macbookair-midnight-1.png"] }, { name: "Starlight", hex: "#f0e6d8", images: ["/img/macbookair-starlight-1.png"] }, { name: "Sky Blue", hex: "#a8c3d6", images: ["/img/macbookair-skyblue-1.png"] }, { name: "Silver", hex: "#e5e5e5", images: ["/img/macbookair-silver-1.png"] }],
    storage: [{ label: "256GB SSD", delta: 0 }, { label: "512GB SSD", delta: 600 }],
    description: {
      he: "MacBook Air עם שבב M2 — דק, שקט לחלוטין וסוללה שמחזיקה יום שלם.",
      ar: "MacBook Air بشريحة M2 — رفيع، صامت تماماً وبطارية تدوم يوماً كاملاً.",
      en: "MacBook Air with the M2 chip — thin, completely silent, and battery that lasts all day.",
    },
  },
  {
    id: "12",
    slug: "dell-xps-13",
    name: "Dell XPS 13",
    categoryId: "computers",
    brand: "dell",
    icon: "laptop",
    price: 4990,
    image: "/img/xps13.png",
    images: ["/img/xps13.png","/img/xps13-2.png"],
    colors: [{ name: "Platinum Silver", hex: "#c9cbcd" }, { name: "Graphite", hex: "#3a3b3e" }],
    storage: [{ label: "512GB SSD", delta: 0 }, { label: "1TB SSD", delta: 500 }],
    description: {
      he: "Dell XPS 13 — מחשב Windows קומפקטי עם מסך InfinityEdge ובנייה מאלומיניום.",
      ar: "Dell XPS 13 — حاسوب Windows مدمج بشاشة InfinityEdge وهيكل ألومنيوم.",
      en: "Dell XPS 13 — a compact Windows laptop with an InfinityEdge display and aluminum build.",
    },
  },
  {
    id: "5",
    slug: "steam-deck",
    name: "Steam Deck",
    categoryId: "gaming",
    brand: "other",
    icon: "console",
    badge: "hot",
    price: 2490,
    image: "/img/steamdeck.png",
    images: ["/img/steamdeck.png","/img/steamdeck-2.jpg"],
    storage: [{ label: "256GB", delta: 0 }, { label: "512GB", delta: 450 }, { label: "1TB OLED", delta: 1100 }],
    description: {
      he: "Steam Deck — קונסולת גיימינג ניידת שמריצה את כל ספריית המשחקים שלך מכל מקום.",
      ar: "Steam Deck — جهاز ألعاب محمول يشغّل مكتبة ألعابك بالكامل من أي مكان.",
      en: "Steam Deck — a handheld gaming console that runs your whole library, anywhere.",
    },
  },
  {
    id: "13",
    slug: "ps5-dualsense",
    name: "PS5 DualSense",
    categoryId: "gaming",
    brand: "sony",
    icon: "console",
    price: 290,
    image: "/img/dualsense-white-1.png",
    images: ["/img/dualsense-white-1.png","/img/dualsense.png","/img/dualsense-2.png"],
    colors: [{ name: "White", hex: "#eceae6", images: ["/img/dualsense-white-1.png"] }, { name: "Midnight Black", hex: "#1c1c1e", images: ["/img/dualsense-midnightblack-1.png"] }, { name: "Cosmic Red", hex: "#9c2b2b", images: ["/img/dualsense-cosmicred-1.png"] }, { name: "Starlight Blue", hex: "#5f7a99", images: ["/img/dualsense-starlightblue-1.png"] }],
    description: {
      he: "בקר DualSense ל-PS5 עם משוב הפטי ומקשי טריגר אדפטיביים.",
      ar: "يد تحكم DualSense لجهاز PS5 مع استجابة لمسية ومفاتيح تحفيز تكيفية.",
      en: "DualSense controller for PS5 with haptic feedback and adaptive triggers.",
    },
  },
  {
    id: "7",
    slug: "gaming-headset-pro",
    name: "Gaming Headset Pro",
    categoryId: "gaming",
    brand: "other",
    icon: "headset",
    badge: "hot",
    price: 490,
    image: "/img/headset.jpg",
    images: ["/img/headset.jpg"],
    colors: [{ name: "Black", hex: "#1c1c1e" }, { name: "White", hex: "#eceae6" }],
    description: {
      he: "אוזניות גיימינג עם סאונד סראונד ומיקרופון לביטול רעשים.",
      ar: "سماعة ألعاب بصوت محيطي ومايكروفون لإلغاء الضوضاء.",
      en: "Gaming headset with surround sound and a noise-cancelling microphone.",
    },
  },
  {
    id: "6",
    slug: "apple-watch-s9",
    name: "Apple Watch S9",
    categoryId: "accessories",
    brand: "apple",
    icon: "watch",
    price: 1890,
    image: "/img/watchs9-midnight-1.png",
    images: ["/img/watchs9-midnight-1.png","/img/watch9.jpg","/img/watch9-2.jpg"],
    colors: [{ name: "Midnight", hex: "#1d1d1f", images: ["/img/watchs9-midnight-1.png"] }, { name: "Starlight", hex: "#f0e6d8", images: ["/img/watchs9-starlight-1.png"] }, { name: "Silver", hex: "#e5e5e5", images: ["/img/watchs9-silver-1.png"] }, { name: "(PRODUCT)RED", hex: "#a72032", images: ["/img/watchs9-red-1.png"] }],
    storage: [{ label: "41mm", delta: 0 }, { label: "45mm", delta: 150 }],
    variant2Label: "size",
    description: {
      he: "Apple Watch Series 9 עם שבב S9, מסך בהיר יותר ומעקב בריאות מתקדם.",
      ar: "Apple Watch Series 9 بشريحة S9، شاشة أكثر سطوعاً وتتبع صحي متقدم.",
      en: "Apple Watch Series 9 with the S9 chip, a brighter display and advanced health tracking.",
    },
  },
  {
    id: "8",
    slug: "galaxy-buds3",
    name: "Galaxy Buds3",
    categoryId: "accessories",
    brand: "samsung",
    icon: "buds",
    price: 590,
    image: "/img/buds.png",
    images: ["/img/buds.png"],
    colors: [{ name: "Graphite", hex: "#3a3b3e" }, { name: "White", hex: "#eceae6" }, { name: "Silver", hex: "#c9cbcd" }],
    description: {
      he: "Galaxy Buds3 עם ביטול רעשים אקטיבי וסאונד עשיר.",
      ar: "Galaxy Buds3 بإلغاء ضوضاء نشط وصوت غني.",
      en: "Galaxy Buds3 with active noise cancellation and rich sound.",
    },
  },
  {
    id: "14",
    slug: "fast-charger-65w",
    name: "Fast Charger 65W",
    categoryId: "accessories",
    brand: "other",
    icon: "charger",
    price: 120,
    image: "/img/charger.jpg",
    images: ["/img/charger.jpg","/img/charger-2.jpg"],
    description: {
      he: "מטען מהיר 65W תואם לרוב הטלפונים והמחשבים הניידים.",
      ar: "شاحن سريع 65 واط متوافق مع معظم الهواتف وأجهزة الحاسوب المحمولة.",
      en: "65W fast charger, compatible with most phones and laptops.",
    },
  },
  {
    id: "15",
    slug: "iphone-17",
    name: "iPhone 17",
    categoryId: "phones",
    brand: "apple",
    icon: "phone",
    badge: "new",
    price: 3690,
    image: "/img/iphone17-black-1.png",
    images: ["/img/iphone17-black-1.png","/img/iphone17-1.png","/img/iphone17-2.jpg"],
    colors: [{ name: "Black", hex: "#1c1c1e", images: ["/img/iphone17-black-1.png"] }, { name: "White", hex: "#f0e6d8", images: ["/img/iphone17-white-1.png"] }, { name: "Lavender", hex: "#c9c2d9", images: ["/img/iphone17-lavender-1.png"] }, { name: "Sage", hex: "#a9b79a", images: ["/img/iphone17-sage-1.png"] }, { name: "Mist Blue", hex: "#a9c0cf", images: ["/img/iphone17-mistblue-1.png"] }],
    storage: [{ label: "256GB", delta: 0 }, { label: "512GB", delta: 450 }],
    description: {
      he: "iPhone 17 עם שבב A19, מסך ProMotion 120Hz וגוף אלומיניום קל.",
      ar: "iPhone 17 بشريحة A19 وشاشة ProMotion 120Hz وهيكل ألومنيوم خفيف.",
      en: "iPhone 17 with the A19 chip, a 120Hz ProMotion display and a light aluminum body.",
    },
  },
  {
    id: "16",
    slug: "iphone-17-pro",
    name: "iPhone 17 Pro",
    categoryId: "phones",
    brand: "apple",
    icon: "phone",
    badge: "new",
    price: 4990,
    image: "/img/iphone17pro-deepblue-1.png",
    images: ["/img/iphone17pro-deepblue-1.png","/img/iphone17pro-1.png","/img/iphone17pro-2.jpg"],
    colors: [{ name: "Deep Blue", hex: "#22334a", images: ["/img/iphone17pro-deepblue-1.png"] }, { name: "Silver", hex: "#e5e5e5", images: ["/img/iphone17pro-silver-1.png"] }, { name: "Cosmic Orange", hex: "#a3552b", images: ["/img/iphone17pro-cosmicorange-1.png"] }],
    storage: [{ label: "256GB", delta: 0 }, { label: "512GB", delta: 450 }, { label: "1TB", delta: 950 }],
    description: {
      he: "iPhone 17 Pro עם שבב A19 Pro, מצלמת Pro Fusion 48MP ועיצוב יוניבודי.",
      ar: "iPhone 17 Pro بشريحة A19 Pro وكاميرا Pro Fusion 48MP وتصميم Unibody.",
      en: "iPhone 17 Pro with the A19 Pro chip, a 48MP Pro Fusion camera and a unibody design.",
    },
  },
  {
    id: "17",
    slug: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    categoryId: "phones",
    brand: "apple",
    icon: "phone",
    badge: "new",
    price: 5490,
    image: "/img/iphone17promax-deepblue-1.png",
    images: ["/img/iphone17promax-deepblue-1.png","/img/iphone17promax-1.png","/img/iphone17promax-2.jpg"],
    colors: [{ name: "Deep Blue", hex: "#22334a", images: ["/img/iphone17promax-deepblue-1.png"] }, { name: "Silver", hex: "#e5e5e5", images: ["/img/iphone17promax-silver-1.png"] }, { name: "Cosmic Orange", hex: "#a3552b", images: ["/img/iphone17promax-cosmicorange-1.png"] }],
    storage: [{ label: "256GB", delta: 0 }, { label: "512GB", delta: 450 }, { label: "1TB", delta: 950 }, { label: "2TB", delta: 1900 }],
    description: {
      he: "iPhone 17 Pro Max — המסך הכי גדול, הסוללה הכי חזקה, אותו שבב A19 Pro.",
      ar: "iPhone 17 Pro Max — أكبر شاشة وأقوى بطارية، بنفس شريحة A19 Pro.",
      en: "iPhone 17 Pro Max — the biggest screen and battery, the same A19 Pro chip.",
    },
  },
  {
    id: "18",
    slug: "macbook-pro-14",
    name: "MacBook Pro 14\"",
    categoryId: "computers",
    brand: "apple",
    icon: "laptop",
    price: 8990,
    image: "/img/macbookpro-spaceblack-1.png",
    images: ["/img/macbookpro-spaceblack-1.png","/img/macbookpro-1.png","/img/macbookpro-2.png"],
    colors: [{ name: "Space Black", hex: "#2b2b2b", images: ["/img/macbookpro-spaceblack-1.png","/img/macbookpro-spaceblack-2.png"] }, { name: "Silver", hex: "#e5e5e5", images: ["/img/macbookpro-silver-1.png","/img/macbookpro-silver-2.png"] }],
    storage: [{ label: "512GB SSD", delta: 0 }, { label: "1TB SSD", delta: 700 }],
    description: {
      he: "MacBook Pro 14 אינץ׳ עם שבב M4 ומסך Liquid Retina XDR — לעבודה מקצועית.",
      ar: "MacBook Pro 14 إنش بشريحة M4 وشاشة Liquid Retina XDR — للعمل الاحترافي.",
      en: "14\" MacBook Pro with the M4 chip and a Liquid Retina XDR display — for pro workflows.",
    },
  },
  {
    id: "19",
    slug: "ipad-pro",
    name: "iPad Pro",
    categoryId: "tablets",
    brand: "apple",
    icon: "tablet",
    price: 4290,
    image: "/img/ipadpro-spaceblack-1.png",
    images: ["/img/ipadpro-spaceblack-1.png","/img/ipadpro-1.png","/img/ipadpro-2.png"],
    colors: [{ name: "Space Black", hex: "#2b2b2b", images: ["/img/ipadpro-spaceblack-1.png"] }, { name: "Silver", hex: "#e5e5e5", images: ["/img/ipadpro-silver-1.png"] }],
    storage: [{ label: "256GB", delta: 0 }, { label: "512GB", delta: 500 }, { label: "1TB", delta: 1200 }],
    description: {
      he: "iPad Pro עם שבב M4 ומסך Ultra Retina XDR — הטאבלט הכי חזק של אפל.",
      ar: "iPad Pro بشريحة M4 وشاشة Ultra Retina XDR — أقوى جهاز لوحي من آبل.",
      en: "iPad Pro with the M4 chip and an Ultra Retina XDR display — Apple's most powerful tablet.",
    },
  },
  {
    id: "20",
    slug: "ipad",
    name: "iPad",
    categoryId: "tablets",
    brand: "apple",
    icon: "tablet",
    price: 1690,
    image: "/img/ipadbase-blue-1.png",
    images: ["/img/ipadbase-blue-1.png"],
    colors: [{ name: "Blue", hex: "#7fa7c9", images: ["/img/ipadbase-blue-1.png"] }, { name: "Pink", hex: "#e3b8c4", images: ["/img/ipadbase-pink-1.png"] }, { name: "Silver", hex: "#e5e5e5", images: ["/img/ipadbase-silver-1.png"] }, { name: "Yellow", hex: "#e8d27a", images: ["/img/ipadbase-yellow-1.png"] }],
    storage: [{ label: "128GB", delta: 0 }, { label: "256GB", delta: 300 }],
    description: {
      he: "iPad — הכי משתלם, מושלם לגלישה, לימודים ובידור יומיומי.",
      ar: "iPad — الأكثر قيمة مقابل السعر، مثالي للتصفح والدراسة والترفيه اليومي.",
      en: "iPad — the best value, perfect for everyday browsing, study and play.",
    },
  },
  {
    id: "21",
    slug: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2",
    categoryId: "accessories",
    brand: "apple",
    icon: "watch",
    price: 3390,
    image: "/img/watchultra2-naturaltitanium-1.png",
    images: ["/img/watchultra2-naturaltitanium-1.png","/img/watchultra2-1.png","/img/watchultra2-2.png"],
    colors: [{ name: "Natural Titanium", hex: "#8a8479", images: ["/img/watchultra2-naturaltitanium-1.png"] }, { name: "Black Titanium", hex: "#2b2a28", images: ["/img/watchultra2-blacktitanium-1.png"] }],
    storage: [{ label: "49mm", delta: 0 }],
    description: {
      he: "Apple Watch Ultra 2 — עמיד, עם GPS מדויק וסוללה שמחזיקה ימים.",
      ar: "Apple Watch Ultra 2 — متين، مع GPS دقيق وبطارية تدوم أياماً.",
      en: "Apple Watch Ultra 2 — rugged, with precise GPS and multi-day battery life.",
    },
  },
  {
    id: "22",
    slug: "airpods-pro-2",
    name: "AirPods Pro 2",
    categoryId: "accessories",
    brand: "apple",
    icon: "buds",
    price: 990,
    image: "/img/airpodspro-default-1.png",
    images: ["/img/airpodspro-default-1.png"],
    description: {
      he: "AirPods Pro 2 עם ביטול רעשים אקטיבי ואודיו מרחבי מותאם אישית.",
      ar: "AirPods Pro 2 بإلغاء ضوضاء نشط وصوت مكاني مخصص.",
      en: "AirPods Pro 2 with active noise cancellation and personalized spatial audio.",
    },
  },
  {
    id: "23",
    slug: "airpods-4",
    name: "AirPods 4",
    categoryId: "accessories",
    brand: "apple",
    icon: "buds",
    price: 590,
    image: "/img/airpods4-default-1.png",
    images: ["/img/airpods4-default-1.png","/img/airpods4-default-2.png"],
    description: {
      he: "AirPods 4 — עיצוב חדש, סאונד עשיר יותר וסוללה משופרת.",
      ar: "AirPods 4 — تصميم جديد، صوت أغنى وبطارية محسّنة.",
      en: "AirPods 4 — a new design, richer sound and improved battery life.",
    },
  },
  {
    id: "24",
    slug: "galaxy-s25-ultra",
    name: "Galaxy S25 Ultra",
    categoryId: "phones",
    brand: "samsung",
    icon: "phone",
    badge: "new",
    price: 5190,
    image: "/img/s25ultra-titaniumgray-1.png",
    images: ["/img/s25ultra-titaniumgray-1.png","/img/s25ultra-1.jpg","/img/s25ultra-2.jpg"],
    colors: [{ name: "Titanium Gray", hex: "#b3ab9e", images: ["/img/s25ultra-titaniumgray-1.png"] }, { name: "Titanium Black", hex: "#4a4a4d", images: ["/img/s25ultra-titaniumblack-1.png"] }, { name: "Titanium Silverblue", hex: "#8e9fbc", images: ["/img/s25ultra-titaniumsilverblue-1.png"] }, { name: "Titanium Whitesilver", hex: "#d9d9d6", images: ["/img/s25ultra-titaniumwhitesilver-1.png"] }],
    storage: [{ label: "256GB", delta: 0 }, { label: "512GB", delta: 450 }, { label: "1TB", delta: 950 }],
    description: {
      he: "Galaxy S25 Ultra עם בינה מלאכותית מתקדמת, עט S Pen ומצלמה בזום גבוה.",
      ar: "Galaxy S25 Ultra بذكاء اصطناعي متقدم وقلم S Pen وكاميرا بتقريب عالٍ.",
      en: "Galaxy S25 Ultra with advanced on-device AI, the built-in S Pen and a high-zoom camera.",
    },
  },
  {
    id: "25",
    slug: "galaxy-s25",
    name: "Galaxy S25",
    categoryId: "phones",
    brand: "samsung",
    icon: "phone",
    badge: "new",
    price: 3590,
    image: "/img/s25-1.png",
    images: ["/img/s25-1.png"],
    colors: [{ name: "Navy", hex: "#22334a" }, { name: "Silver Shadow", hex: "#c9cbcd" }, { name: "Mint", hex: "#a9c9ba" }],
    storage: [{ label: "128GB", delta: 0 }, { label: "256GB", delta: 350 }],
    description: {
      he: "Galaxy S25 — קומפקטי וחזק, עם מסך Dynamic AMOLED וביצועים מעולים.",
      ar: "Galaxy S25 — مدمج وقوي، بشاشة Dynamic AMOLED وأداء ممتاز.",
      en: "Galaxy S25 — compact and powerful, with a Dynamic AMOLED display and excellent performance.",
    },
  },
  {
    id: "26",
    slug: "galaxy-watch7",
    name: "Galaxy Watch7",
    categoryId: "accessories",
    brand: "samsung",
    icon: "watch",
    price: 1490,
    image: "/img/watch7-1.jpg",
    images: ["/img/watch7-1.jpg"],
    colors: [{ name: "Green", hex: "#4a6a52" }, { name: "Cream", hex: "#e8dfc8" }, { name: "Silver", hex: "#c9cbcd" }],
    storage: [{ label: "40mm", delta: 0 }, { label: "44mm", delta: 150 }],
    variant2Label: "size",
    description: {
      he: "Galaxy Watch7 עם מעקב בריאות מתקדם וסוללה שמחזיקה ימים.",
      ar: "Galaxy Watch7 بتتبع صحي متقدم وبطارية تدوم أياماً.",
      en: "Galaxy Watch7 with advanced health tracking and multi-day battery life.",
    },
  },
  {
    id: "27",
    slug: "playstation-5",
    name: "PlayStation 5",
    categoryId: "gaming",
    brand: "sony",
    icon: "console",
    badge: "new",
    price: 2190,
    image: "/img/ps5-1.png",
    images: ["/img/ps5-1.png","/img/ps5-2.png"],
    colors: [{ name: "White", hex: "#eceae6", images: ["/img/ps5-white-1.png"] }],
    storage: [{ label: "Digital Edition", delta: 0 }, { label: "Disc Edition", delta: 300 }],
    description: {
      he: "PlayStation 5 עם משחקים ב-4K וזמני טעינה כמעט מיידיים.",
      ar: "PlayStation 5 بألعاب 4K وأوقات تحميل شبه فورية.",
      en: "PlayStation 5 with 4K gaming and near-instant load times.",
    },
  },
]
